### ISSUE TITLE
Elastic 5.0 support

### ISSUE THREAD

**Issue by bermanjosh** [bitemyapp/bloodhound#157] opened 2016-11-29 12:40 UTC
Hey,

I've been working on getting bloodhound to work against Elastic 5.0, here:
https://github.com/bermanjosh/bloodhound/tree/es5

It's not a fully-featured fork, but I've got I think I've got the major semantic changes (such as Filters), and all the tests pass. I've been slowly incorporating this into my application, and I've got a working POC (some testing is still outstanding, though).

I know in the past we've discussed trying to keep compatibility and sharing modules, but wasn't able to find a clean way to get that to work. I'm opening this issue for you guys to see what I've done, and decide if it's something you'd like to try to work back in. 

Please let me know what you think.

**Comment by bitemyapp** [comment] 2016-11-29 16:35
>but wasn't able to find a clean way to get that to work.

Yeah this doesn't surprise me at all. One way forward is to make the repo dual package.

Let us take the temperature of things. @MichaelXavier - what do you think? Where's Amazon's ES support at? I think they support 1.5 and 2.3 at the moment: https://aws.amazon.com/elasticsearch-service/faqs/

So, for decent coverage we'd need a bloodhound-1, bloodhound-2, bloodhound-(5|current).

@bermanjosh the commit that your branch is ahead on, is that all that was needed to bring bloodhound up to compatibility with 5.x? All tests passing?

**Comment by bermanjosh** [comment] 2016-11-29 16:38
@bitemyapp
All tests pass, yes.

I squashed everything into one commit. 
https://github.com/bermanjosh/bloodhound/commit/437bc3d16f00bb2de339a682e3df866d0518e94d

**Comment by MichaelXavier** [comment] 2016-11-29 18:52
I'm no longer using the Amazon ES service for the typical reasons you'd expect with any new-ish AWS product launch. I'm running my own cluster on 1.7. However, I'd say the main reason why I'm on 1 and not 2 is due to bloodhound not officially supporting 2, so its kind of a catch 22. FWIW (small sample size) most people I talk to (non Haskellers, naturally) are on ES 2 or 5.

I'd be willing to go to 2 for now. I have no objection to going to 5 either but I'm pretty sure you want to do major version upgrades 1 at a time. I'm not sure how well either the fork or master works on 2, but I imagine any upgrade would result in downtime: you'd bring the app down, snapshot, restore to the new cluster, bring the new version of the app online with the newer bloodhound. I think that's going to be the hard sell but its gotta happen eventually.

Elastic has put us in a tough spot, these type changes look like they'd be pretty hard to reconcile. Does anyone know how likely it is for the v5 client to work on v2 (seriously what is with this dumbass version scheme)? If that is more reasonable maybe we could do that.

The main question to ask here is what factor makes us drop support? 1.7.4 came out Dec 2015. I'm not convinced Amazon is a good barometer since they generally support (and sometimes cap out) at old versions of stuff. I'm also not convinced they're very widely used. I personally had to write a separate package to even do auth on their service.

**Comment by bitemyapp** [comment] 2016-11-29 19:30
@MichaelXavier I know Elasticsearch moves fast, but Dec. 2015 isn't that long ago in my view.

I guess the big question before we get into implementation is, do we want to tackle concurrent version support? Do we have the labor for it? Prima facie seems like types module gets namespaced by version and _maybe_ we can share some of the tests and the client.

**Comment by MichaelXavier** [comment] 2016-11-29 21:18
Yep, 1 year isn't too long, I agree.

I think we'll need to do concurrent support. Even if we decided to drop 1, I think we still have a bunch of people on 2 and 5. Not doing version spanning seems like it puts our releases on Elastic's and they have way more resources. Also, I could see us maybe only tracking 1 version of ES if we had a complete API coverage, but BH has always been add APIs as needed, so for covering missing across versions turns into crazy backporting.

The labor I'm not sure. I'm not sure how thrilled my job would be about me taking point on this. I've been meaning to look at what was new in ES2 and see if any of it would solve real problems for us. I think it got the reindex API in 2 which actually would have saved my ass a few times. I've put quite a bit of work into the BH test suite so I can definitely help with slicing up the test suite, adding new ES versions to the matrix, etc.

Another thing I'm curious about: I wonder if ES has published a standard test suite for client implementers. Certainly we won't cover it completely, but it may be able to break up the tests by pulling that test list at 1.X, 2.X. Adding new features could basically be just enabling a larger portion of that suite, and it would be easy to see if it backports to the previous version.

**Comment by MichaelXavier** [comment] 2016-11-30 03:07
Scratch the part about a standard test suite. I must have been thinking of some other project. I can't find any such thing with elasticsearch. The other language test suites I looked at basically hardly tested anything at all.

**Comment by bermanjosh** [comment] 2016-11-30 04:05
* They jumped from 2 to 5 to match the rest of their stack
* Clusters cannot be upgraded from 1 to 5, you have to go to 2 in the middle (and do a cluster restart). We'll probably just skip the upgrade completely, and rebuild the index directly on 5 (all our info is persisted elsewhere). 
* I don't know what it's worth, but I was at an Elastic meetup last week, and during the Q&A I mentioned that I'm on Haskell and gave bloodhound a shout-out. Afterwards, one of the SAs came up to me and told me that they like functional stuff over there (they're using Scala in-house), and said he *might* be able to get us some free bandwidth from some of the elastic devs. Even if that comes through, what would our ask be?
* My gut on this is to have people who need 1.7 stay on bloodhound 0.12, move the package forward to 5.0, and backport any relevant changes to 0.12.1 (etc...) for 6 months or so. If we want to keep supporting both, then I'd say separate packages, and not try to have them reuse code. I don't think planning to desperate 1.7 in 6 months is unfair. That being said, I'm obviously biased, as I know I'm migrating over to es 5.0 over the next month or two.

**Comment by bitemyapp** [comment] 2016-11-30 15:24
>Even if that comes through, what would our ask be?

I personally wouldn't want them to do anything Bloodhound specific, I'd want them to develop and maintain either an end-to-end test suite intended for validating clients or to write and maintain a complete API spec. I've been asking for the latter on the assumption it would be less work and have blown it off several times. If we can't get them to consider either of those things...then I guess I'd just ask them to examine what it's like for someone that doesn't know Elasticsearch to attempt to use ES with and without Bloodhound. I've known Bloodhound users who didn't even know Haskell, they were just using Bloodhound to generate the JSON for copy-pasta because that was easier than using the native bindings. I've mentioned this to a couple ES devs before. What do you think you'd like @MichaelXavier?

>My gut on this is to have people who need 1.7 stay on bloodhound 0.12, move the package forward to 5.0, and backport any relevant changes to 0.12.1 (etc...)

My inclination is that if we're going to do concurrent support at all (which has a high upfront cost), we might as well add 1.x to the list. Rather not have multiple timelines of versions getting pushed to Hackage, I make mistakes uploading releases as it is.

**Comment by MichaelXavier** [comment] 2016-11-30 17:00
You pretty much nailed it. I'm not really sure how to read the intent of them dedicating bandwidth for us. I think the best use of the time is to first and foremost to come up with a json schema for their APIs and (and this part is important) *integrate it into their automated test suite*. Almost all of the pain from adding features to the client comes from trying to unify their examples and what the server reports into types. We inevitably get it wrong because there will just be features missing from different platforms or systems with different capabilities. I have a feeling that if they tried to commit to a spec today almost everything would be marked as nullable (or worse, incorrectly marked as not nullable). Ultimately, my hope is them committing to a spec will make plain the inconsistencies in their API and they'll do something about it.

Adding a client test suite is also pretty helpful but it seems like more work to me and much easier to screw up. I'm not exactly sure how it would work in a way that supported other languages.

I took a quick look at some of the client libraries in other languages and in all the community-supported clients I looked at, none of their readmes even *mentioned* what version of ES they target, what to do if you use an older version, etc, so the bar is very low. The only clients I found that seem to be taking breaking API changes seriously at all are the official ES ones. Those declare a major version cutoff, i.e. 1.X for ES 1.0, 2.x for ES 2.0. Since the Haskell PVP requires breaking changes bump *either* A or B in A.B.C, this would be doable for us. If we looked at this somewhat optimistically, I'll bet the majority of the features we get are usually compatible with 2 and 5. What if we targeted the latest with master, and kept branches for 1 and 2? We'd set up the travis.yaml in those branches to build against the relevant ES version. If someone has a vested interest of backporting a feature/fix to an older version (I suspect this will be rare), they PR to that branch and we do an upload. I know you don't want to have multiple version timelines but I'm betting it'll be rare in practice. Also I don't remember if hackage supports out of sequence uploads.

**Comment by MichaelXavier** [comment] 2016-12-01 03:00
@bermanjosh where is your es5 branch not as being complete (as in complete ES API coverage, that may never happen) but in terms not feature parity with upstream? If you're close, maybe the right thing to do is to merge it into a branch on bloodhound, test it against ES5 on travis and also try to backport it to an ES2 branch (which is what I'm targeting because I'm on 1 right now). Maybe when you're at parity we can just move dev effort into this repo and start pushing this forward!

**Comment by bitemyapp** [comment] 2016-12-01 03:03
@MichaelXavier @bermanjosh having consulted with my coworkers on this, I'm opposed to doing this via git branches. Git is about dev stuff and I don't like what it would do to the Hackage releases.

I'd prefer to namespace the modules by major ES version and share whatever code can be shared. I'm willing to do a spike to make this happen as well.

How strongly do you feel about the branches + concurrent releases approach?

**Comment by MichaelXavier** [comment] 2016-12-01 03:24
I'm willing to be convinced about the modules approach. You have 2 dimensions to worry about here: types and APIs. For instance, 1, 2, and 5 all have the concept of creating a mapping but the versions can expect different types for the mapping and response. How do we do that? 

One way I could see doing it is have totally separate trees for types and the public APIs. There will be overlap, but untangling the types when they change across versions is less messy, e.g. what if 2 and 5 have the same type of something but not 1? You could move the type-generic stuff into a shared, internal module: it encodes the route and how to post the message but stays generic that the input has `ToJSON`, response has `FromJSON`, then each version's module uses their own type to make it concrete, e.g. `createIndexG :: (MonadBH m, ToJSON settings, FromJSON resp) => settings -> IndexName -> m resp`. That way we keep standard error handling and we don't have to recreate the API surface area. Implementations for any version could even just alias to this function and specify with the types the actual response type for haddocks and usability. If you don't support a feature (e.g. in 2 or 5 they dropped deleteMapping), they don't import it.

Looking at the perspective of contributions, I think everyone who is contributing to Bloodhound is doing so because they need something for work. They will ensure its tested and working on their version but I think you'll get resistance for them ensuring it works with older versions: they now have to juggle ES versions on their machine and I just don't think they'll do it. So instead if we have separate module trees, if I contribute a feature for ES5, I do it in the 5 module tree, add my tests and they pass. If I or someone cares to volunteer to backport it (or even forwardport it!) they can take on that responsibility. I think that's a pretty square deal for contributors. @bermanjosh would probably contribute an API for 5. If I'm still on 2 and I want it, I'll do the work. I wouldn't expect him to.

**Comment by bermanjosh** [comment] 2016-12-01 06:30
@MichaelXavier :
> @bermanjosh where is your es5 branch not as being complete (as in complete ES API coverage, that may never happen) but in terms not feature parity with upstream? 
I think I'm like a week or two behind master. I'll rebase and PR without renaming any module, for testing purposes. Then, once we decide how to rename modules, I will. 

Regarding shared modules: I spent time on #101 working with that approach, trying to keep as much shared as possible, but there was a lot that ended up being specialized. So unless we're thinking of doing a lot of work to pass deal with a monad or something to specialize it down low, we should be prepared for a lot of code duplication. For sure the types won't match up too well, but even the APIs are already diverging and, I assume, will continue to diverge farther.

**Comment by bitemyapp** [comment] 2016-12-01 18:45
@bermanjosh I'm fine with code duplication upfront, deduplication later as we figure out the warp & weft of what is shared.

**Comment by bermanjosh** [comment] 2016-12-03 18:53
@bitemyapp Ok, so practically, what do you want my next steps to be? Move everything to version-specific modules?

**Comment by bitemyapp** [comment] 2016-12-03 21:45
That's my preference going forward. @MichaelXavier are you comfortable with that? Any preferences on nomenclature?

**Comment by codedmart** [comment] 2016-12-07 13:24
@bermanjosh I have added a few things in my fork for my needs. I need to read through your changes and see if I did anything different I may be able to contribute back. Is this something that might be merged in the soonish future? Should I PR off of your branch for anything I may be interested in adding or wait till this is merged upstream?

**Comment by bermanjosh** [comment] 2016-12-08 14:29
@codedmart I had to stop fighting with travis for a few days, i'm hoping to get back to this early next week. 

I feel it's better to wait until everything decided and merged here before forking again, but that's just my opinion.

**Comment by codedmart** [comment] 2016-12-08 14:30
Fair enough, just let me know if I can help out at all.

**Comment by bermanjosh** [comment] 2016-12-08 14:31
Honestly, I have no idea why the last CI failed. I have zero experince with travis beyond this. If you want to take a 30 second look to see if I didn't something stupid, I'd appreceate it.

**Comment by codedmart** [comment] 2016-12-08 14:50
@bermanjosh Haven't read into it much, but the connection to es is refused. From a few googles I am not sure if it is because es5 is only listening on ipv6 by default of if the default listening host has changed in some way. I will try to read more into it if you haven't resolved it based on this information.

**Comment by bermanjosh** [comment] 2016-12-08 14:52
I thought the connection was closed because es died  [here](https://travis-ci.org/bitemyapp/bloodhound/jobs/181253159#L427), I just have no idea *why*.

**Comment by MichaelXavier** [comment] 2016-12-11 19:52
Out of memory perhaps?

**Comment by bermanjosh** [comment] 2016-12-11 19:55
Interesting idea. Any idea how I can get stats on that?

**Comment by bermanjosh** [comment] 2016-12-13 19:08
@MichaelXavier @bitemyapp 
I think you're right, I think it's a memory issue. I setup the Travis docker image locally, and the tests ran fine. I did some searching, and the "killed" termenology is linked to out of memory.

Do you guys have experence or ideas how to deal with this? I tried building with a -j1, but it didn't help. I spent a decent amount of time on this today, and I'm at a loss as to how to get Travis to not be annoying.

**Comment by codedmart** [comment] 2016-12-13 19:29
@bermanjosh I also don't have a ton of experience with travis, but can you try disabling the container based travis infrastructure?

**Comment by MichaelXavier** [comment] 2016-12-13 23:03
Maybe try `ES_HEAP_SIZE=750M`. I think the default is 1G. Definitely not recommended for ES where it matters but in test maybe we'll be fine.

**Comment by bermanjosh** [comment] 2016-12-14 04:24
@MichaelXavier - Good call. That one test passes now. I'll reactivate all the tests and squash all this nonesense in a few hours.

**Comment by bermanjosh** [comment] 2016-12-15 10:12
Turns out you can't rebase well after you've pushed. So, I just made more of a mess. Hurray. 

Ok, so , assuming Travis doesn't hate me anymore, what's next?

**Comment by bermanjosh** [comment] 2016-12-15 10:35
Travis is having a seizure. The same commit passed on the PR in your repo, and died in my repo. 
[Good](https://travis-ci.org/bitemyapp/bloodhound/builds/184188959) - [Bad](https://travis-ci.org/bermanjosh/bloodhound/builds/184188940)

For #159 (which didn't touch this), the opposite happened. 
[Bad](https://travis-ci.org/bitemyapp/bloodhound/builds/184183956) - [Good](https://travis-ci.org/bermanjosh/bloodhound/builds/184183922)

**Comment by MichaelXavier** [comment] 2016-12-15 20:13
That test failure looks legit. The issue is that its running quickcheck in CI and every once in a while it will find an ambiguous parse case in one of the parsers, but it gets reseeded next time and passes. I've created #160 to help identify these cases more readily. I'll wager if you run `stack test --test-arguments "--seed 704012937"` that failure will repro. I've created #161 and self-assigned to deal with that, so don't sweat it.

**Comment by bermanjosh** [comment] 2016-12-15 20:33
@MichaelXavier Ok, thanks. Seeing it twice on two separate PRs a few minutes apart made me wonder if I was missing something.

**Comment by MichaelXavier** [comment] 2016-12-19 16:41
Just an update: resolved both #160 and #161.

**Comment by bermanjosh** [comment] 2016-12-22 05:45
@bitemyapp 
From my perspective, absent any further instructions from you, I think this is ready to roll.

**Comment by bitemyapp** [comment] 2016-12-22 07:59
@bermanjosh Looks like there's a merge conflict? I'll give 'er another look in the meantime.

**Comment by MichaelXavier** [comment] 2017-01-26 20:33
@bermanjosh @bitemyapp So now that we have a green master, did we want to wait for more features (perhaps #164) or are we ready for the release? Obviously this will be a breaking release since we have a different module hierarchy, so this should be going out at `0.13.0.0` or `1.0.0.0` if the marketing department is bored.

**Comment by bitemyapp** [comment] 2017-01-26 20:42
I'm prepared to leave whether we cut a release or after #164 up to @bermanjosh 

I don't care much re: version numbers but I would slightly prefer `0.13.0.0` just because I don't think we're any less prepared to break things if needed even if it's a psychological/implicit thing.

**Comment by bermanjosh** [comment] 2017-01-27 06:33
I'm also for `0.13.0.0` - since we're not a complete API, I'm less into `1.0.0.0`. 

Let's release after I finish #164. I should be able to get it done after weekend.

**Comment by bitemyapp** [comment] 2017-01-27 08:37
Sounds good to me, thank you @bermanjosh!

**Comment by bermanjosh** [comment] 2017-01-31 05:34
I think we're ready to close this issue, right?

**Comment by bitemyapp** [comment] 2017-01-31 17:55
Yah

**Closed by bitemyapp** 2017-01-31 17:55 UTC
